#! /usr/bin/env python3
# -*- coding: utf-8 -*-
# SPDX-License-Identifier: GPL-2.0-or-later

import email
import email.generator
import os
import subprocess
import sys

__author__ = 'Christian Brauner <brauner@kernel.org>'

msgid_script = os.path.expandvars('$HOME/src/bin/generate-msgid')
new_msgid = subprocess.check_output(msgid_script, text=True)

patch = sys.argv[1]
f_patch = open(patch, 'r+')

msg = email.message_from_file(f_patch)

del msg['Message-Id']
msg.__setitem__('Message-Id', '<{}>'.format(new_msgid))

f_patch.seek(0)

val = msg.get_unixfrom()
gen = email.generator.Generator(f_patch)
flattened = gen.flatten(msg, unixfrom=False if val is None else True)

f_patch.truncate()
os.fsync(f_patch)
f_patch.close()

subprocess.run(['patatt', 'sign', '--hook', patch], check=True)
